export const APP_IMAGES = {
  smartEnergy: "/smartEnergy.webp",
  solarPowerStation: "/solarPowerStation.webp",
  finalLogo: "/final-logo-png-4x-1.png",
  footerLogo: "/logo_with_font.png",
  image7: "/image7.webp",
  image8: "/image8.webp",
  image5: "/image5.webp",
  image6: "/image6.webp",
  image4: "/image4.webp",
  phone1401: "/phonecover.webp",
  sun21: "/sun.png",
  smartHouse1: "/smarthouse.png",
  technicianSolarPanels: "/technicianSolarPanels.webp",
  digitalTablet: "/digitaltablet.webp",
  iconSavings: "/IconSavings.svg",
  iconEnergy: "/iconEnergy.svg",
  iconEco: "/iconEco.svg",
  iconAuto: "/iconAuto.svg",
  iconEmail: "/iconEmail.svg",
  iconPhone: "/iconPhone.svg",
  iconLocation: "/iconLocation.svg",
  iconSmartHome: "/iconSmartHome.svg",

  aboutHero: "/aboutHero.webp",
  aboutLogo: "/logo_with_font.png",
  aboutIdea: "/aboutIdea.png",
  aboutWalk: "/aboutWalk.png",
  aboutForSale: "/aboutForSale.png",
  aboutSmartHome: "/aboutSmartHome.png",
  aboutAvatar: "/96272e93cd756ab385e25714009039f290d0b16d.png",
  aboutSocialX: "/Icon-3.svg",
  aboutSocialIn: "/Icon-4.svg",

  appIcon1: "/appIcon01.svg",
  appIcon2: "/appIcon02.svg",
  appIcon3: "/appIcon03.svg",
  appIcon4: "/appIcon04.svg",

  teamSrinath: "/team-srinath.webp",
  teamHariprasad: "/team-hariprasad.webp",
  teamParvathi: "/team-parvathi.webp",
  teamSelvaNancy: "/team-selva-nancy.webp",
  teamRajeev: "/team-rajeev.webp",

  solutionsVideo: "/VID-20251219-WA0000.mp4",
  solutionsSolarHouse: "/solutionsSolarHouse.webp",
  solutionsSmartHomeScene: "/solutionsSmartHomeScene.webp",
  solutionsAppPhoneHero: "/image12.webp",
  solutionsAppPhoneInsights: "/image4.webp",
  solutionsAppPhoneMonitor: "/image7.webp",
  solutionsAppPhoneModes: "/image10.webp",
} as const;
